blend2bam --texture copy Army.blend ../outward/assets/Army.bam
blend2bam --texture copy Factory.blend ../outward/assets/Factory.bam
blend2bam --texture copy Farm.blend ../outward/assets/Farm.bam
blend2bam --texture copy Living.blend ../outward/assets/LivingQuarters.bam
blend2bam --texture copy Mine.blend ../outward/assets/Mine.bam
blend2bam --texture copy Tower.blend ../outward/assets/Tower.bam
blend2bam --texture copy Shield.blend ../outward/assets/Shield.bam
blend2bam --texture copy WaterRefinery.blend ../outward/assets/WaterRefinery.bam
blend2bam --texture embed Ground.blend ../outward/assets/Ground.bam
